---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: lb-test
  name: lb-test
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: lb-test-service
spec:
  selector:
    run: lb-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
