apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
spec:
  containers:
  - image: registry1.dso.mil/ironbank/redhat/ubi/ubi9:9.3
    name: mirror-test
    resources: {}
    imagePullPolicy: Always
    command: ["sleep", "3600"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  # imagePullSecrets:
  # - name: private-registry